-- ==============================================================================
-- MIGRACIÓN 025: ESTÁNDAR AWP (CWA, CWP, EWP, IWP, PWP) Y EXTENSIÓN DE SOPORTES
-- Soporte para Advanced Work Packaging en todo el ciclo de piping
-- ==============================================================================

-- 1. Añadir atributos AWP a entidades principales de piping
ALTER TABLE piping.lineas
  ADD COLUMN IF NOT EXISTS cwa VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS cwp VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS ewp VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS iwp VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS pwp VARCHAR(64) NULL;

ALTER TABLE piping.isometricos
  ADD COLUMN IF NOT EXISTS cwa VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS cwp VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS ewp VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS iwp VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS pwp VARCHAR(64) NULL;

ALTER TABLE piping.spools
  ADD COLUMN IF NOT EXISTS cwa VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS cwp VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS ewp VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS iwp VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS pwp VARCHAR(64) NULL;

ALTER TABLE piping.juntas
  ADD COLUMN IF NOT EXISTS cwa VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS cwp VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS ewp VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS iwp VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS pwp VARCHAR(64) NULL;

ALTER TABLE piping.valvulas
  ADD COLUMN IF NOT EXISTS cwa VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS cwp VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS ewp VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS iwp VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS pwp VARCHAR(64) NULL;

-- 2. Extensión de atributos en piping.soportes
ALTER TABLE piping.soportes
  ADD COLUMN IF NOT EXISTS item_numero VARCHAR(32) NULL,
  ADD COLUMN IF NOT EXISTS cwa VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS cwp VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS ewp VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS iwp VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS pwp VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS codigo_linea VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS codigo_iso VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS clase VARCHAR(32) NULL,
  ADD COLUMN IF NOT EXISTS tipo_soporte VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS diametro_nps VARCHAR(32) NULL,
  ADD COLUMN IF NOT EXISTS cantidad NUMERIC(10, 2) DEFAULT 1,
  ADD COLUMN IF NOT EXISTS unidad VARCHAR(16) DEFAULT 'un',
  ADD COLUMN IF NOT EXISTS peso_kg NUMERIC(12, 4) NULL,
  ADD COLUMN IF NOT EXISTS suministro VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS observaciones TEXT NULL,
  ADD COLUMN IF NOT EXISTS created_by UUID NULL,
  ADD COLUMN IF NOT EXISTS updated_by UUID NULL;

-- Constraint de unicidad para sincronización atómica
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uq_soportes_proy_codigo'
    ) THEN
        ALTER TABLE piping.soportes ADD CONSTRAINT uq_soportes_proy_codigo UNIQUE (proyecto_id, codigo);
    END IF;
END $$;
